eiger/metric/urls.py
from django.urls import URLPattern, URLResolver, path

from eiger.metric.views import graph_view

urlpatterns: list[URLPattern | URLResolver] = [
    path('graphs', graph_view, name='graphs')
]

eiger/moonboard/urls.py
from django.urls import URLPattern, URLResolver, path

from eiger.moonboard.views import (
    RegisterMoonboardAccount,
    unregister_moonboard_account_view,
)

urlpatterns: list[URLPattern | URLResolver] = [
    path(
        'register',
        RegisterMoonboardAccount.as_view(),
        name='register-moonboard-account',
    ),
    path(
        'unregister',
        unregister_moonboard_account_view,
        name='unregister-moonboard-account',
    ),
]

eiger/trainers/urls.py
from django.urls import URLPattern, URLResolver, path

from eiger.trainers.views import (
    home_view,
    retrieve_category_sub_categoriess_view,
    retrieve_exercise_view,
    update_exercise_view,
)

urlpatterns: list[URLPattern | URLResolver] = [
    path('home/', home_view, name='trainer-home'),
    path(
        'exercises/<int:exercise_id>',
        retrieve_exercise_view,
        name='retrieve_exercise',
    ),
    path(
        'exercises/<int:exercise_id>/',
        update_exercise_view,
        name='update_exercise',
    ),
    path(
        'categories/<int:category_id>/exercise-types',
        retrieve_category_sub_categoriess_view,
        name='retrieve_category_sub_categoriess',
    ),
]

eiger/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path
from health_check import urls as health_urls

from eiger.authentication import urls as auth_urls
from eiger.authentication.views import (
    climber_index_view,
    set_user_timezone_offset_view,
    trainer_index_view,
)
from eiger.metric import urls as metrics_urls
from eiger.moonboard import urls as moonboard_urls
from eiger.trainers import urls as trainers_urls
from eiger.training_plan import urls as training_plan_urls

urlpatterns: list[URLPattern | URLResolver] = [
    path('', climber_index_view, name='climber-index'),
    path('trainer/', trainer_index_view, name='trainer-index'),
    path('auth/', include(auth_urls)),
    path('trainers/', include(trainers_urls)),
    path('training-plan/', include(training_plan_urls)),
    path('moonboard/', include(moonboard_urls)),
    path('metrics/', include(metrics_urls)),
    path(
        'set-user-timezone-offset/',
        set_user_timezone_offset_view,
        name='set-user-timezone-offset',
    ),
    # path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    # Health checks:
    path('healthcheck/', include(health_urls)),
]

if settings.DEBUG:  # pragma: no cover
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns += [
        # URLs specific only to django-debug-toolbar:
        path('__debug__/', include('debug_toolbar.urls')),
        # Serving static files in development only:
        *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    ]

eiger/authentication/models.py
from django.contrib.auth.models import User
from django.db import models

from eiger.core.models import BaseModel


class Climber(BaseModel):
    related_name = 'climbers'
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    trainer = models.ForeignKey(
        'Trainer',
        null=True,
        default=None,
        on_delete=models.SET_NULL,
        related_name=related_name,
    )


class Trainer(BaseModel):
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)

eiger/core/models.py
from uuid import uuid4

from django.db import models
from django.utils.translation import gettext_lazy as _


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4)
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text=_('The timestamp when the object was created.'),
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text=_('The timestamp when the object was last updated.'),
    )

    class Meta:
        abstract = True

eiger/moonboard/models.py
from enum import Enum

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from eiger.authentication.models import Climber
from eiger.core.models import BaseModel


class HoldHorizontalCoordinates(str, Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    G = 'G'
    H = 'H'
    I = 'I'  # noqa
    J = 'J'
    K = 'K'


class HoldVerticalCoordinates(Enum):
    ONE = '1'
    TWO = '2'
    THREE = '3'
    FOUR = '4'
    FIVE = '5'
    SIX = '6'
    SEVEN = '7'
    EIGHT = '8'
    NINE = '9'
    TEN = '10'
    ELEVEN = '11'
    TWELVE = '12'
    THIRTEEN = '13'
    FOURTEEN = '14'
    FIFTEEN = '15'
    SIXTEEN = '16'
    SEVENTEEN = '17'
    EIGHTEEN = '18'


class AccountData(BaseModel):
    climber = models.OneToOneField(Climber, on_delete=models.CASCADE)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)


class HoldSetup(BaseModel):
    description = models.CharField(max_length=255)
    angle = models.CharField(max_length=2)
    api_id = models.PositiveIntegerField()


class Boulder(BaseModel):
    name = models.CharField(max_length=255, db_index=True)
    grade = models.CharField(max_length=4, db_index=True)
    setter_user_id = models.CharField(max_length=36, blank=True)
    setter_name = models.CharField(max_length=255, blank=True)
    method = models.CharField(max_length=255)
    user_rating = models.PositiveSmallIntegerField(db_index=True)
    repeats = models.PositiveIntegerField(db_index=True)
    hold_setup = models.ForeignKey(
        to=HoldSetup, on_delete=models.CASCADE, related_name='boulders'
    )
    is_benchmark = models.BooleanField(db_index=True)
    is_master = models.BooleanField()
    upgraded = models.BooleanField()
    downgraded = models.BooleanField()
    api_id = models.PositiveIntegerField()
    date_inserted = models.DateTimeField()
    date_updated = models.DateTimeField(null=True)
    date_deleted = models.DateTimeField(null=True)
    has_beta_video = models.BooleanField()


def validate_hold(value: str):
    if not 1 < len(value) < 4:
        raise ValidationError(
            _('%(value)s length is not valid'),
            params={'value': value},
        )
    if not value.isalnum():
        raise ValidationError(
            _('%(value)s is not alphanumeric'),
            params={'value': value},
        )

    if not value[0].isalpha() or not value[1:].isdigit():
        raise ValidationError(
            _('%(value)s is not a valid hold definition'),
            params={'value': value},
        )


class Move(BaseModel):
    boulder = models.ForeignKey(
        to=Boulder, on_delete=models.CASCADE, related_name='moves'
    )
    hold = models.CharField(
        max_length=3, validators=[validate_hold], db_index=True
    )
    is_start = models.BooleanField()
    is_end = models.BooleanField()


class LogbookEntry(BaseModel):
    related_name = 'completed_boulders'
    id = models.IntegerField(primary_key=True)
    boulder = models.ForeignKey(
        'Boulder', on_delete=models.CASCADE, related_name=related_name
    )
    climber = models.ForeignKey(
        Climber, on_delete=models.CASCADE, related_name=related_name
    )
    date_climbed = models.DateTimeField()
    comment = models.TextField()
    user_grade = models.CharField(max_length=4)
    attempts = models.CharField(max_length=20)

    @property
    def has_flashed(self) -> bool:
        return self.attempts == 1

eiger/moonboard/forms.py
from django import forms

from eiger.moonboard.models import AccountData


class AccountDataForm(forms.ModelForm):
    class Meta:
        model = AccountData
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

eiger/authentication/views.py
from typing import Type, TypedDict

import structlog
from django.contrib.auth import login
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_GET, require_POST

from eiger.authentication.forms import (
    CreateClimberForm,
    CreateTrainerForm,
    LoginClimberForm,
    LoginTrainerForm,
)

logger = structlog.get_logger()


class ContextData(TypedDict):
    cleaned_data: dict[str, str]
    errors: dict[str, list[str]]


class Context(TypedDict):
    registration: ContextData
    login: ContextData


# Create your views here.
@require_GET
def climber_index_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user accessing the index view.')
    registration_form: Type[CreateClimberForm] = CreateClimberForm
    login_form: Type[LoginClimberForm] = LoginClimberForm

    context: Context = request.session.get('context', {})
    if registration_data := context.get('registration'):
        registration_form: CreateClimberForm = (  # type: ignore[no-redef]
            registration_form()
        )
        registration_form.cleaned_data = registration_data.get(
            'cleaned_data', {}
        )
        for field, error in registration_data.get('errors', {}).items():
            registration_form.add_error(
                field=field, error=error  # type: ignore[call-arg, arg-type]
            )
        logger.debug(
            'Added to the registration form the errors %s.',
            registration_form.errors,
        )

    if login_data := context.get('login'):
        login_form: LoginClimberForm = login_form()  # type: ignore[no-redef]
        login_form.cleaned_data = login_data.get('cleaned_data', {})
        login_form._errors = login_data.get(  # type: ignore[attr-defined]
            'errors'
        )
        logger.debug(
            'Added to the login form the errors %s.',
            login_form._errors,  # type: ignore[attr-defined]
        )

    request.session.flush()
    logger.debug('Flushed the request session.')

    return render(
        request=request,
        template_name='pages/climbers/index.html',
        context={
            'registration_form': registration_form,
            'login_form': login_form,
        },
    )


@require_POST
def climber_registration_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending registration data.')
    form = CreateClimberForm(request.POST)
    if not form.is_valid():
        request.session['context'] = {
            'registration': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
            'login': None,
        }
        logger.debug(
            'Added the registration form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='climber-index')

    user = form.save()
    logger.info('Created the user %s.', user)
    login(request, user)
    return redirect(to='climber-home')


@require_POST
def climber_login_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending login data.')
    form = LoginClimberForm(
        request,
        data=request.POST,
    )
    if not form.is_valid():
        request.session['context'] = {
            'registration': None,
            'login': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
        }
        logger.debug(
            'Added the login form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='climber-index')

    user = form.get_user()
    logger.debug('Retrieved the user %s given the form data.', user)
    login(request, user)
    return redirect(to='climber-home')


@require_POST
def set_user_timezone_offset_view(request: HttpRequest) -> JsonResponse:
    timezone_offset = int(request.POST.get('timezone_offset', 0))
    request.session['user_timezone_offset'] = timezone_offset
    request.session.save()
    return JsonResponse({'message': 'Timezone offset updated successfully'})


@require_GET
def trainer_index_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user accessing the index view.')
    registration_form: Type[CreateTrainerForm] = CreateTrainerForm
    login_form: Type[LoginTrainerForm] = LoginTrainerForm

    context: Context = request.session.get('context', {})
    if registration_data := context.get('registration'):
        registration_form: CreateClimberForm = (  # type: ignore[no-redef]
            registration_form()
        )
        registration_form.cleaned_data = registration_data.get(
            'cleaned_data', {}
        )
        for field, error in registration_data.get('errors', {}).items():
            registration_form.add_error(
                field=field, error=error  # type: ignore[call-arg, arg-type]
            )
        logger.debug(
            'Added to the registration form the errors %s.',
            registration_form.errors,
        )

    if login_data := context.get('login'):
        login_form: LoginTrainerForm = login_form()  # type: ignore[no-redef]
        login_form.cleaned_data = login_data.get('cleaned_data', {})
        login_form._errors = login_data.get(  # type: ignore[attr-defined]
            'errors'
        )
        logger.debug(
            'Added to the login form the errors %s.',
            login_form._errors,  # type: ignore[attr-defined]
        )

    request.session.flush()
    logger.debug('Flushed the request session.')

    return render(
        request=request,
        template_name='pages/trainers/index.html',
        context={
            'registration_form': registration_form,
            'login_form': login_form,
        },
    )


@require_POST
def trainer_registration_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending registration data.')
    form = CreateTrainerForm(request.POST)
    if not form.is_valid():
        request.session['context'] = {
            'registration': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
            'login': None,
        }
        logger.debug(
            'Added the registration form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='trainer-index')

    user = form.save()
    logger.info('Created the user %s.', user)
    login(request, user)
    return redirect(to='trainer-home')


@require_POST
def trainer_login_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending login data.')
    form = LoginTrainerForm(
        request,
        data=request.POST,
    )
    if not form.is_valid():
        request.session['context'] = {
            'registration': None,
            'login': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
        }
        logger.debug(
            'Added the login form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='trainer-index')

    user = form.get_user()
    logger.debug('Retrieved the user %s given the form data.', user)
    login(request, user)
    return redirect('trainer-home')

eiger/metric/views.py
# Create your views here.

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET

from eiger.authentication.services import (
    ClimberHttpRequest,
    climber_access_only,
)
from eiger.moonboard.models import AccountData
from eiger.moonboard.services import (
    retrieve_boulder_count_by_climbed_date,
    retrieve_completed_workouts_exercise_category,
    retrieve_number_of_attempts_boulder_name_grade_and_date_climbed,
    retrieve_number_of_benchmark_boulders_completed_by_grade,
    retrieve_total_number_of_benchmark_boulders_by_grade,
)


@login_required(login_url='/')
@climber_access_only
@require_GET
def graph_view(request: ClimberHttpRequest) -> HttpResponse:
    climber = request.climber
    context = {
        'completed_workouts_exercise_category_data': list(
            retrieve_completed_workouts_exercise_category(climber=climber)
        )
    }

    if AccountData.objects.filter(climber=climber).exists():
        context['benchmark_boulders_by_grade_proportion_climber_data'] = list(
            retrieve_number_of_benchmark_boulders_completed_by_grade(
                climber=climber
            )
        )
        context['total_benchmark_boulders_by_grade_proportion_data'] = list(
            retrieve_total_number_of_benchmark_boulders_by_grade()
        )
        context[
            'number_of_attempts_boulder_name_grade_and_date_climbed_data'
        ] = list(
            retrieve_number_of_attempts_boulder_name_grade_and_date_climbed(
                climber=climber
            )
        )
        context['retrieve_boulder_count_by_climbed_date_data'] = list(
            retrieve_boulder_count_by_climbed_date(climber=climber)
        )

    return render(request, 'pages/climbers/graph_template.html', context)

eiger/workout/views.py
# Create your views here.

eiger/templates/pages/trainers/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <!-- Page title -->
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <style>
        #page-container {
            position: relative;
            min-height: 100vh;
        }

        #content-wrap {
            padding-bottom: 2.5rem; /* Footer height */
        }

        .no-styling {
            all: unset;
        }
    </style>
    {% block style %}
    {% endblock style %}
  </head>
  <body>
    <div id="page-container">
      {% include 'components/trainers/navbar.html' %}
      <main id="content-wrap" class="bg-white">
        <div class="container my-4">
          {% block content %}
          {% endblock content %}
        </div>
      </main>
      {% include 'components/footer.html' %}
    </div>
    <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    <script src="https://unpkg.com/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

eiger/templates/pages/trainers/edit_exercise.html
{% extends 'pages/trainers/base.html' %}

{% load i18n static %}

{% block title %}
  {{ _("Climb Hard - Edit Exercise") }}
{% endblock title %}
{% block style %}
  <style>
        .alert {
            margin-top: 0.5rem;
        }

        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
            padding: 0.75rem 1.25rem;
            border-radius: 0.25rem;
        }
  </style>
{% endblock style %}
{% block content %}
  <div class="container">
    <h1>Edit Exercise</h1>
    <form method="post" action="{% url 'update_exercise' exercise.id %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_sub_categories">Type:</label>
        {{ form.sub_category }}
        {% if form.errors.sub_category %}
          <div class="alert alert-danger">{{ form.errors.sub_category }}</div>
        {% endif %}
      </div>
      <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
        {% if form.errors.name %}
          <div class="alert alert-danger">{{ form.errors.name }}</div>
        {% endif %}
      </div>
      <div class="form-group">
        <label for="id_description">Description:</label>
        {{ form.description }}
        {% if form.errors.description %}
          <div class="alert alert-danger">{{ form.errors.description }}</div>
        {% endif %}
      </div>
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
{% endblock content %}

eiger/templates/pages/trainers/home.html
{% extends 'pages/trainers/base.html' %}

{% load i18n static %}

{% block title %}
    {{ _("Climb Hard - Home") }}
{% endblock title %}
{% block style %}
    <style>
        .exercise-card {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 12px 12px 6px;
            margin-bottom: 12px;
        }

        .exercise-card .exercise-header {
            display: flex;
            justify-content: space-between;
        }

        .exercise-card .exercise-header .edit-icon {
            font-size: 1.4rem; /* Adjust the font size as desired */
            color: #333; /* Adjust the color of the icon */
            margin-right: 5px; /* Adjust the spacing between the icon and the exercise name */
        }

        .exercise-card .exercise-name {
            font-size: 1.4rem;
            margin-top: 0;
            margin-bottom: 8px;
        }

        .exercise-card .exercise-tags {
            display: flex;
            align-items: center;
            margin-bottom: 6px;
        }

        .exercise-card .exercise-tags .badge {
            margin-right: 4px;
            font-size: 0.8rem;
            padding: 4px 8px;
        }

        .exercise-card .exercise-details {
            margin-top: 12px;
        }

        .exercise-card .exercise-description-row {
            display: flex;
            justify-content: space-between;
        }

        .exercise-card .exercise-description-row .exercise-description {
            font-size: 0.9rem;
            margin-bottom: 6px;
        }

        .exercise-card .exercise-created-by {
            color: #888;
            font-size: 0.8rem;
            margin-top: 8px;
            margin-bottom: 4px;
        }

    </style>
{% endblock style %}
{% block content %}
    <div class="container">
        <h1>My Pending Review Exercises</h1>
        <div class="row">
            <div class="col-md-6">
                <h2>Exercises</h2>
                {% if not pending_exercises %}
                    <div class="d-flex flex-column justify-content-center mt-3">
                        <p>
                            {{ _("You do not have any Exercise pending a review.") }}
                        </p>
                        <a class="btn btn-primary" href="{% url 'training-plan-creation' %}">
                            {{ _("Add an Exercise") }}
                        </a>
                    </div>
                {% else %}
                    {% for exercise in pending_exercises %}
                        <div class="exercise-card pending-exercises-card">
                            <div class="exercise-header">
                                <h4 class="exercise-name">{{ exercise.name }}</h4>
                                <a href="{% url 'retrieve_exercise' exercise.id %}" class="edit-icon">
                                    <i class="fas fa-edit"></i>
                                </a>
                            </div>
                            <div class="exercise-tags">
              <span style="background-color: {{ exercise.sub_category.category.color }}"
                    class="badge">{{ exercise.sub_category }}</span>
                            </div>
                            <p class="exercise-description">{{ exercise.description }}</p>
                            <p class="exercise-created-by">Created by: {{ exercise.created_by }}</p>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

eiger/templates/pages/trainers/index.html
{% extends 'pages/trainers/base.html' %}

{% load i18n static %}

{% block title %}
  {{ _("Climb Hard - Trainers") }}
{% endblock title %}
{% block style %}
  <style>
    small {
        color: grey
    }

    .password-reset-link {
        margin-top: 1em
    }
  </style>
{% endblock style %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card border-0 shadow-lg my-5">
          <div class="card-body p-5">
            <h2 class="text-center mb-4">Climb Hard - Trainers</h2>
            <hr />
            <div class="row mt-4">
              <div id="login-component" class="col-md-6">
                {% if login_form.errors and not login_form.non_field_errors %}
                  <p class="errornote">
                    {% blocktranslate count counter=login_form.errors.items|length %}Please correct
                                            the
                                            error below.{% plural %}Please correct the errors
                                            below.{% endblocktranslate %}
                  </p>
                {% endif %}
                {% if login_form.non_field_errors %}
                  {% for error in login_form.non_field_errors %}
                    <p class="errornote">{{ error }}</p>
                  {% endfor %}
                {% endif %}
                <form method="post" id="login-form" action="{% url 'login' %}">
                  {% csrf_token %}
                  <h3 class="mb-3">Log In</h3>
                  <div class="form-row">
                    {{ login_form.username.errors }}
                    {{ login_form.username.label_tag }} {{ login_form.username }}
                  </div>
                  <div class="form-row">
                    {{ login_form.password.errors }}
                    {{ login_form.password.label_tag }} {{ login_form.password }}
                    <input type="hidden" name="next" value="{{ next }}" />
                  </div>
                  <div class="password-reset-link">
                    <a href="{{ password_reset_url }}">{% translate 'Forgotten your password or username?' %}</a>
                  </div>
                  <div class="mb-3">
                    <button id="login-input" type="submit" class="btn btn-primary">
                      {% translate 'Log In' %}
                    </button>
                  </div>
                </form>
              </div>
              <div id="register-component" class="col-md-6">
                {% if form.errors and not form.non_field_errors %}
                  <p class="errornote">
                    {% blocktranslate count counter=form.errors.items|length %}Please correct
                                            the error below.{% plural %}Please correct the errors
                                            below.{% endblocktranslate %}
                  </p>
                {% endif %}
                {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                    <p class="errornote">{{ error }}</p>
                  {% endfor %}
                {% endif %}
                <form method="post" id="register-form" action="{% url 'register' %}">
                  {% csrf_token %}
                  <h3 class="mb-3">Sign Up</h3>
                  <div class="form-row">
                    {{ registration_form.username.errors }}
                    {{ registration_form.username.label_tag }} {{ registration_form.username }}
                    <br />
                    <small>{{ registration_form.username.help_text }}</small>
                  </div>
                  <div class="form-row">
                    {{ registration_form.password1.errors }}
                    {{ registration_form.password1.label_tag }} {{ registration_form.password1 }}
                    <br />
                    <small>{{ registration_form.password1.help_text }}</small>
                    <input type="hidden" name="next" value="{{ next }}" />
                  </div>
                  <div class="form-row">
                    {{ registration_form.password2.errors }}
                    {{ registration_form.password2.label_tag }} {{ registration_form.password2 }}
                    <br />
                    <small>{{ registration_form.password2.help_text }}</small>
                    <input type="hidden" name="next" value="{{ next }}" />
                  </div>
                  <div class="mb-3">
                    <button id="register-input" type="submit" class="btn btn-primary">
                      {% translate 'Register' %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}