eiger/metric/urls.py
from django.urls import URLPattern, URLResolver, path

from eiger.metric.views import graph_view

urlpatterns: list[URLPattern | URLResolver] = [
    path('graphs', graph_view, name='graphs')
]

eiger/moonboard/urls.py
from django.urls import URLPattern, URLResolver, path

from eiger.moonboard.views import (
    RegisterMoonboardAccount,
    unregister_moonboard_account_view,
)

urlpatterns: list[URLPattern | URLResolver] = [
    path(
        'register',
        RegisterMoonboardAccount.as_view(),
        name='register-moonboard-account',
    ),
    path(
        'unregister',
        unregister_moonboard_account_view,
        name='unregister-moonboard-account',
    ),
]

eiger/trainers/urls.py
from django.urls import URLPattern, URLResolver, path

from eiger.trainers.views import (
    home_view,
    retrieve_category_sub_categoriess_view,
    retrieve_exercise_view,
    update_exercise_view,
)

urlpatterns: list[URLPattern | URLResolver] = [
    path('home/', home_view, name='trainer-home'),
    path(
        'exercises/<int:exercise_id>',
        retrieve_exercise_view,
        name='retrieve_exercise',
    ),
    path(
        'exercises/<int:exercise_id>/',
        update_exercise_view,
        name='update_exercise',
    ),
    path(
        'categories/<int:category_id>/exercise-types',
        retrieve_category_sub_categoriess_view,
        name='retrieve_category_sub_categoriess',
    ),
]

eiger/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path
from health_check import urls as health_urls

from eiger.authentication import urls as auth_urls
from eiger.authentication.views import (
    climber_index_view,
    set_user_timezone_offset_view,
    trainer_index_view,
)
from eiger.metric import urls as metrics_urls
from eiger.moonboard import urls as moonboard_urls
from eiger.trainers import urls as trainers_urls
from eiger.training_plan import urls as training_plan_urls

urlpatterns: list[URLPattern | URLResolver] = [
    path('', climber_index_view, name='climber-index'),
    path('trainer/', trainer_index_view, name='trainer-index'),
    path('auth/', include(auth_urls)),
    path('trainers/', include(trainers_urls)),
    path('training-plan/', include(training_plan_urls)),
    path('moonboard/', include(moonboard_urls)),
    path('metrics/', include(metrics_urls)),
    path(
        'set-user-timezone-offset/',
        set_user_timezone_offset_view,
        name='set-user-timezone-offset',
    ),
    # path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    # Health checks:
    path('healthcheck/', include(health_urls)),
]

if settings.DEBUG:  # pragma: no cover
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns += [
        # URLs specific only to django-debug-toolbar:
        path('__debug__/', include('debug_toolbar.urls')),
        # Serving static files in development only:
        *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    ]

eiger/authentication/models.py
from django.contrib.auth.models import User
from django.db import models

from eiger.core.models import BaseModel


class Climber(BaseModel):
    related_name = 'climbers'
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    trainer = models.ForeignKey(
        'Trainer',
        null=True,
        default=None,
        on_delete=models.SET_NULL,
        related_name=related_name,
    )


class Trainer(BaseModel):
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)

eiger/training_plan/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from eiger.authentication.models import Climber
from eiger.core.models import BaseModel


class Week(BaseModel):
    training_plan = models.ForeignKey('TrainingPlan', on_delete=models.CASCADE)
    number = models.IntegerField()

    class Meta:
        unique_together = ('training_plan', 'number')


class Day(BaseModel):
    week = models.ForeignKey(Week, on_delete=models.CASCADE)
    day_of_the_week_choices = [
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
        ('sunday', 'Sunday'),
    ]
    day_of_the_week = models.CharField(
        max_length=9, choices=day_of_the_week_choices
    )
    date = models.DateField()
    notes = models.TextField()

    class Meta:
        unique_together = ('day_of_the_week', 'week')


class TrainingPlan(BaseModel):
    name = models.CharField(max_length=255)
    climber = models.ForeignKey(
        Climber, on_delete=models.CASCADE, related_name='training_plans'
    )
    starting_date = models.DateField()
    description = models.TextField()

    created_by_type = models.ForeignKey(
        ContentType,
        on_delete=models.SET_NULL,
        null=True,
        related_name='created_training_plans',
    )
    created_by_id = models.UUIDField()
    created_by = GenericForeignKey('created_by_type', 'created_by_id')

eiger/workout/models.py
from typing import Optional

from django.db import models
from django.utils.translation import gettext_lazy as _

from eiger.core.models import BaseModel
from eiger.trainers.models import Exercise
from eiger.training_plan.models import Day


class RPE(BaseModel):
    scale = models.PositiveSmallIntegerField()
    description = models.TextField()
    display_text = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.display_text


class TargetTimeUnit(models.TextChoices):
    MINUTES = 'minutes', _('Minutes')
    SECONDS = 'seconds', _('Seconds')


class Workout(BaseModel):
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    sets = models.PositiveSmallIntegerField(default=1)
    rest_per_set_in_seconds = models.PositiveSmallIntegerField(
        null=True, help_text=_('The duration of rest between sets in seconds.')
    )
    target_repetitions = models.PositiveSmallIntegerField(null=True)
    rest_per_repetition_in_seconds = models.PositiveSmallIntegerField(
        null=True,
        help_text=_('The duration of rest between repetitions in seconds.'),
    )
    target_time_in_seconds = models.PositiveSmallIntegerField(null=True)
    target_time_unit = models.CharField(
        blank=True, choices=TargetTimeUnit.choices, max_length=7
    )
    target_weight_in_kilos = models.PositiveSmallIntegerField(null=True)

    @property
    def target_time(self) -> Optional[int]:
        return (
            self.target_time_in_seconds // 60
            if self.target_time_unit == TargetTimeUnit.MINUTES.value
            else self.target_time_in_seconds
        )

    @property
    def rest_per_set(self) -> Optional[int]:
        return (
            self.rest_per_set_in_seconds // 60
            if self.target_time_unit == TargetTimeUnit.MINUTES.value
            else self.rest_per_set_in_seconds
        )

    @property
    def rest_per_repetition(self) -> Optional[int]:
        return (
            self.rest_per_repetition_in_seconds // 60
            if self.target_time_unit == TargetTimeUnit.MINUTES
            else self.rest_per_repetition_in_seconds
        )


class CompletedWorkout(BaseModel):
    workout = models.OneToOneField(Workout, on_delete=models.CASCADE)
    perceived_rpe = models.ForeignKey(
        RPE,
        on_delete=models.CASCADE,
        null=True,
        related_name='completed_workouts',
    )
    completed_percentage = models.PositiveSmallIntegerField(null=True)
    notes = models.TextField(blank=True)

eiger/moonboard/forms.py
from django import forms

from eiger.moonboard.models import AccountData


class AccountDataForm(forms.ModelForm):
    class Meta:
        model = AccountData
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

eiger/authentication/views.py
from typing import Type, TypedDict

import structlog
from django.contrib.auth import login
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_GET, require_POST

from eiger.authentication.forms import (
    CreateClimberForm,
    CreateTrainerForm,
    LoginClimberForm,
    LoginTrainerForm,
)

logger = structlog.get_logger()


class ContextData(TypedDict):
    cleaned_data: dict[str, str]
    errors: dict[str, list[str]]


class Context(TypedDict):
    registration: ContextData
    login: ContextData


# Create your views here.
@require_GET
def climber_index_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user accessing the index view.')
    registration_form: Type[CreateClimberForm] = CreateClimberForm
    login_form: Type[LoginClimberForm] = LoginClimberForm

    context: Context = request.session.get('context', {})
    if registration_data := context.get('registration'):
        registration_form: CreateClimberForm = (  # type: ignore[no-redef]
            registration_form()
        )
        registration_form.cleaned_data = registration_data.get(
            'cleaned_data', {}
        )
        for field, error in registration_data.get('errors', {}).items():
            registration_form.add_error(
                field=field, error=error  # type: ignore[call-arg, arg-type]
            )
        logger.debug(
            'Added to the registration form the errors %s.',
            registration_form.errors,
        )

    if login_data := context.get('login'):
        login_form: LoginClimberForm = login_form()  # type: ignore[no-redef]
        login_form.cleaned_data = login_data.get('cleaned_data', {})
        login_form._errors = login_data.get(  # type: ignore[attr-defined]
            'errors'
        )
        logger.debug(
            'Added to the login form the errors %s.',
            login_form._errors,  # type: ignore[attr-defined]
        )

    request.session.flush()
    logger.debug('Flushed the request session.')

    return render(
        request=request,
        template_name='pages/climbers/index.html',
        context={
            'registration_form': registration_form,
            'login_form': login_form,
        },
    )


@require_POST
def climber_registration_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending registration data.')
    form = CreateClimberForm(request.POST)
    if not form.is_valid():
        request.session['context'] = {
            'registration': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
            'login': None,
        }
        logger.debug(
            'Added the registration form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='climber-index')

    user = form.save()
    logger.info('Created the user %s.', user)
    login(request, user)
    return redirect(to='climber-home')


@require_POST
def climber_login_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending login data.')
    form = LoginClimberForm(
        request,
        data=request.POST,
    )
    if not form.is_valid():
        request.session['context'] = {
            'registration': None,
            'login': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
        }
        logger.debug(
            'Added the login form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='climber-index')

    user = form.get_user()
    logger.debug('Retrieved the user %s given the form data.', user)
    login(request, user)
    return redirect(to='climber-home')


@require_POST
def set_user_timezone_offset_view(request: HttpRequest) -> JsonResponse:
    timezone_offset = int(request.POST.get('timezone_offset', 0))
    request.session['user_timezone_offset'] = timezone_offset
    request.session.save()
    return JsonResponse({'message': 'Timezone offset updated successfully'})


@require_GET
def trainer_index_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user accessing the index view.')
    registration_form: Type[CreateTrainerForm] = CreateTrainerForm
    login_form: Type[LoginTrainerForm] = LoginTrainerForm

    context: Context = request.session.get('context', {})
    if registration_data := context.get('registration'):
        registration_form: CreateClimberForm = (  # type: ignore[no-redef]
            registration_form()
        )
        registration_form.cleaned_data = registration_data.get(
            'cleaned_data', {}
        )
        for field, error in registration_data.get('errors', {}).items():
            registration_form.add_error(
                field=field, error=error  # type: ignore[call-arg, arg-type]
            )
        logger.debug(
            'Added to the registration form the errors %s.',
            registration_form.errors,
        )

    if login_data := context.get('login'):
        login_form: LoginTrainerForm = login_form()  # type: ignore[no-redef]
        login_form.cleaned_data = login_data.get('cleaned_data', {})
        login_form._errors = login_data.get(  # type: ignore[attr-defined]
            'errors'
        )
        logger.debug(
            'Added to the login form the errors %s.',
            login_form._errors,  # type: ignore[attr-defined]
        )

    request.session.flush()
    logger.debug('Flushed the request session.')

    return render(
        request=request,
        template_name='pages/trainers/index.html',
        context={
            'registration_form': registration_form,
            'login_form': login_form,
        },
    )


@require_POST
def trainer_registration_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending registration data.')
    form = CreateTrainerForm(request.POST)
    if not form.is_valid():
        request.session['context'] = {
            'registration': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
            'login': None,
        }
        logger.debug(
            'Added the registration form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='trainer-index')

    user = form.save()
    logger.info('Created the user %s.', user)
    login(request, user)
    return redirect(to='trainer-home')


@require_POST
def trainer_login_view(request: HttpRequest) -> HttpResponse:
    logger.debug('Received a request for a user sending login data.')
    form = LoginTrainerForm(
        request,
        data=request.POST,
    )
    if not form.is_valid():
        request.session['context'] = {
            'registration': None,
            'login': {
                'cleaned_data': form.cleaned_data,
                'errors': form.errors,
            },
        }
        logger.debug(
            'Added the login form errors %s to the request session.',
            form.errors,
        )
        return redirect(to='trainer-index')

    user = form.get_user()
    logger.debug('Retrieved the user %s given the form data.', user)
    login(request, user)
    return redirect('trainer-home')

eiger/metric/views.py
# Create your views here.

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET

from eiger.authentication.services import (
    ClimberHttpRequest,
    climber_access_only,
)
from eiger.moonboard.models import AccountData
from eiger.moonboard.services import (
    retrieve_boulder_count_by_climbed_date,
    retrieve_completed_workouts_exercise_category,
    retrieve_number_of_attempts_boulder_name_grade_and_date_climbed,
    retrieve_number_of_benchmark_boulders_completed_by_grade,
    retrieve_total_number_of_benchmark_boulders_by_grade,
)


@login_required(login_url='/')
@climber_access_only
@require_GET
def graph_view(request: ClimberHttpRequest) -> HttpResponse:
    climber = request.climber
    context = {
        'completed_workouts_exercise_category_data': list(
            retrieve_completed_workouts_exercise_category(climber=climber)
        )
    }

    if AccountData.objects.filter(climber=climber).exists():
        context['benchmark_boulders_by_grade_proportion_climber_data'] = list(
            retrieve_number_of_benchmark_boulders_completed_by_grade(
                climber=climber
            )
        )
        context['total_benchmark_boulders_by_grade_proportion_data'] = list(
            retrieve_total_number_of_benchmark_boulders_by_grade()
        )
        context[
            'number_of_attempts_boulder_name_grade_and_date_climbed_data'
        ] = list(
            retrieve_number_of_attempts_boulder_name_grade_and_date_climbed(
                climber=climber
            )
        )
        context['retrieve_boulder_count_by_climbed_date_data'] = list(
            retrieve_boulder_count_by_climbed_date(climber=climber)
        )

    return render(request, 'pages/climbers/graph_template.html', context)

eiger/workout/views.py
# Create your views here.

eiger/templates/pages/climbers/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <!-- Page title -->
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <style>
        #page-container {
            position: relative;
            min-height: 100vh;
        }

        #content-wrap {
            padding-bottom: 2.5rem; /* Footer height */
        }

        .no-styling {
            all: unset;
        }
    </style>
    {% block style %}
    {% endblock style %}
  </head>
  <body>
    <div id="page-container">
      {% include 'components/climbers/navbar.html' %}
      <main id="content-wrap" class="bg-white">
        <div class="container my-4">
          {% block content %}
          {% endblock content %}
        </div>
      </main>
      {% include 'components/footer.html' %}
    </div>
    <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
    <script src='https://cdn.plot.ly/plotly-2.25.2.min.js'></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

eiger/templates/pages/climbers/create_training_plan.html
{% extends 'pages/climbers/base.html' %}

{% load i18n static %}
{% load custom_filters %}

{% block title %}
  {{ _("Climb Hard - Create Training Plan") }}
{% endblock title %}
{% block style %}
  <style>
        .alert {
            margin-top: 0.5rem;
        }

        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
            padding: 0.75rem 1.25rem;
            border-radius: 0.25rem;
        }
  </style>
{% endblock style %}
{% block content %}
  <div class="container">
    <h1>{{ _("Create a Training Plan") }}</h1>
    <form method="post" action="{% url 'training-plan-creation' %}">
      {% csrf_token %}
      <div class="form-group">
        {{ form.name.label }}
        {{ form.name }}
        {% if form.errors.name %}
          <div class="alert alert-danger">{{ form.errors.name }}</div>
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.description.label }}
        {{ form.description }}
        {% if form.errors.description %}
          <div class="alert alert-danger">{{ form.errors.description }}</div>
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.number_of_weeks.label }}
        {{ form.number_of_weeks }}
        {% if form.errors.number_of_weeks %}
          <div class="alert alert-danger">{{ form.errors.number_of_weeks }}</div>
        {% endif %}
      </div>
      <label class="form-check-label custom-label-class">
        In which days of the week do you want to train?
      </label>
      <div class="form-group">
        {% for choice_value, choice_label in form.fields.training_days_of_the_week.choices %}
          <div class="form-check">
            <input type="checkbox"
                   name="{{ form.training_days_of_the_week.name }}"
                   id="{{ form.training_days_of_the_week.id_for_label }}_{{ forloop.counter }}"
                   value="{{ choice_value }}"
                   {% if choice_value in form.training_days_of_the_week.value %}
                     checked
                   {% endif %}
                   class="form-check-input">
            <label for="{{ form.training_days_of_the_week.id_for_label }}_{{ forloop.counter }}"
                   class="form-check-label">{{ choice_label }}</label>
          </div>
        {% endfor %}
      </div>
      {% if form.errors.training_days_of_the_week %}
        <div class="alert alert-danger">
          {{ form.errors.training_days_of_the_week }}
        </div>
      {% endif %}
      <div class="form-group">
        {{ form.starting_date.label }}
        {{ form.starting_date }}
        {% if form.errors.starting_date %}
          <div class="alert alert-danger">{{ form.errors.starting_date }}</div>
        {% endif %}
      </div>
      {% include 'components/climbers/save_button.html' %}
    </form>
  </div>
{% endblock content %}

eiger/templates/pages/climbers/create_training_plan_from_shared_url.html
{% extends 'pages/climbers/base.html' %}

{% load i18n static %}
{% load custom_filters %}

{% block title %}
  {{ _("Climb Hard - Create Training Plan") }}
{% endblock title %}
{% block style %}
  <style>
        .alert {
            margin-top: 0.5rem;
        }

        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
            padding: 0.75rem 1.25rem;
            border-radius: 0.25rem;
        }
  </style>
{% endblock style %}
{% block content %}
  <div class="container">
    <h1>{{ _("Create a Training Plan") }}</h1>
    <form method="post"
          action="{% url 'share-training-plan' training_plan_id %}">
      {% csrf_token %}
      <div class="form-group">
        {{ form.starting_date.label }}
        {{ form.starting_date }}
        {% if form.errors.starting_date %}
          <div class="alert alert-danger">{{ form.errors.starting_date }}</div>
        {% endif %}
      </div>
      {% include 'components/climbers/save_button.html' %}
    </form>
  </div>
{% endblock content %}

eiger/templates/pages/climbers/list_exercise_selection.html
{% extends 'pages/climbers/base.html' %}

{% load i18n static %}

{% block title %}
    {{ _("Climb Hard - Exercises") }}
{% endblock title %}
{% block content %}
    <div class="container">
        <h1 class="mt-4">{{ _("Add exercises to day") }}</h1>
        <strong>{{ day.date }} - {{ day.day_of_the_week }}</strong>
        <form method="post" action="{% url 'create-selected-exercises' day.id %}">
            {% csrf_token %}
            <div class="form-check mt-3">
                {% for exercise in form.exercises %}
                    <div class="form-check">
                        <label>
                            <input type="checkbox"
                                   class="form-check-input"
                                   name="exercises"
                                   value="{{ exercise.data.value }}" id="{{ exercise.id_for_label }}"
                                    {% if exercise.data.value in initial_selected_exercises %} checked {% endif %}>
                        </label>
                        <label class="form-check-label" for="{{ exercise.id_for_label }}">
                            {{ exercise.choice_label }}
                        </label>
                        <i class="fa fa-circle-info fa-xs popover-icon"
                           data-bs-toggle="popover"
                           data-bs-placement="top"
                           data-bs-content="{{ exercise.data.value.instance.description }}">
                        </i>
                    </div>
                {% endfor %}
            </div>
            <br>
            {% include 'components/climbers/save_button.html' %}
        </form>
    </div>
{% endblock content %}
{% block scripts %}
    <script>{% include 'js/popovers.js' %}</script>
{% endblock scripts %}

eiger/templates/pages/climbers/register_moonboard_account.html
{% extends 'pages/climbers/base.html' %}

{% load i18n static %}

{% block title %}
  {{ _("Climb Hard - Create Training Plan") }}
{% endblock title %}
{% block content %}
  <div class="container">
    <h1>{{ _("Register your Moonboard Account") }}</h1>
    {% if is_already_registered %}
      <form class="d-flex flex-column justify-content-center mt-5"
            method="post"
            action="{% url 'unregister-moonboard-account' %}">
        {% csrf_token %}
        <label>{{ _("You already have registered a Moonboard account!") }}</label>
        <a class="btn btn btn-outline-primary mt-3" href="{% url 'climber-home' %}">
          {{ _("Back to Home") }}
        </a>
        <button type="submit" class="btn btn-danger mt-3">
          {{ _("Unregister your Moonboard account") }}
        </button>
      </form>
    </div>
  {% else %}
    <form method="post" action="{% url 'register-moonboard-account' %}">
      {% csrf_token %}
      {{ form.as_p }}
      {% include 'components/climbers/save_button.html' %}
    </form>
  {% endif %}
{% endblock content %}

eiger/templates/pages/climbers/retrieve_training_plan.html
{% extends 'pages/climbers/base.html' %}

{% load i18n static custom_filters %}

{% block title %}
  {{ _("Climb Hard - Training Plan") }}
{% endblock title %}
{% block style %}
  <style>
        .alert {
            margin-top: 0.5rem;
        }

        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
            padding: 0.75rem 1.25rem;
            border-radius: 0.25rem;
        }

        .workout-cards {
            font-size: 0.6rem;
        }

        p {
            font-size: 0.8rem;
            color: grey;
        }
  </style>
{% endblock style %}
{% block content %}
  <div class="container">
    <h1>{{ training_plan.name }}</h1>
    <p>{{ training_plan.description }}</p>
    <ul class="nav nav-tabs" id="weeksTabs" role="tablist">
      {% for week in training_plan.week_set.all %}
        <li class="nav-item">
          <a class="nav-link
                    {% if forloop.first %}active{% endif %}"
             id="week-{{ week.id }}-tab"
             data-bs-toggle="tab"
             href="#week-{{ week.id }}"
             role="tab"
             aria-controls="week-{{ week.id }}"
             aria-selected="{% if forloop.first %}
                              true
                            {% else %}
                              false
                            {% endif %}">Week {{ forloop.counter }}</a>
        </li>
      {% endfor %}
    </ul>
    <br />
    <div class="tab-content" id="weeksTabsContent">
      {% for week in training_plan.week_set.all %}
        <div class="tab-pane fade
                    {% if forloop.first %}show active{% endif %}"
             id="week-{{ week.id }}"
             role="tabpanel"
             aria-labelledby="week-{{ week.id }}-tab">
          <div class="row">
            {% for day in week.day_set.all|order_by:'date' %}
              <div class="col-md-4 mb-4">
                <div class="card">
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                      <strong class="card-title mb-0">{{ day.date }} -
                      {{ day.day_of_the_week }}</strong>
                      <a href="{% url 'workouts-for-day' day.id %}" class="edit-icon">
                        <i class="fas fa-edit"></i>
                      </a>
                    </div>
                    <p class="card-text">{{ day.description }}</p>
                    {% if day.workout_set.all %}
                      <div class="workout-cards">
                        <table class="table table-bordered">
                          <thead>
                            <tr>
                              <th>{{ _("Exercise") }}</th>
                              <th>{{ _("Sets") }}</th>
                              <th>{{ _("Reps") }}</th>
                              <th>{{ _("Time") }}</th>
                              <th>{{ _("Weight") }}</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for workout in day.workout_set.all %}
                              <tr>
                                <td>
                                  <i class="fa fa-circle-info popover-icon me-1"
                                     data-bs-toggle="popover"
                                     data-bs-placement="top"
                                     data-bs-content="{{ workout.exercise.description }}">
                                  </i>{{ workout.exercise.name }}
                                </td>
                                <td>{{ workout.sets }}</td>
                                <td>{{ workout.target_repetitions|default_if_none:"-" }}</td>
                                <td>{{ workout.target_time|default_if_none:"-" }}</td>
                                <td>{{ workout.target_weight_in_kilos|default_if_none:"-" }}</td>
                              </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}
{% block scripts %}
  <script>{% include 'js/popovers.js' %}</script>
{% endblock scripts %}